export const posts = [
    {
      id: 1,
      title: "Apple’s Radical iPhone 15 Pro Volume Buttons Almost Definitely Scrapped",
      img: "https://imageio.forbes.com/specials-images/imageserve/641397e79f04500b85460b8f/Apple--iPhone-15--iPhone-15-Pro-Max--iPhone-15-Pro--iPhone-15-Pro-design--iPhone-15/0x0.jpg?format=jpg&crop=923,692,x364,y0,safe&width=960",
      desc: "For weeks, leaks claimed Apple’s most controversial iPhone 15 Pro upgrade had been scrapped. Now one of the company’s key suppliers has confirmed this in a thinly veiled statement to shareholders that is likely to divide opinions among iPhone fans.",
      longDesc:"For weeks, leaks claimed Apple’s most controversial iPhone 15 Pro upgrade had been scrapped. Now one of the company’s key suppliers has confirmed this in a thinly veiled statement to shareholders that is likely to divide opinions among iPhone fans. The supplier is Cirrus Logic, and it provides parts for the haptic (vibration) feedback on iPhones. In November, the company revealed an expanded partnership that would bring a new High-Performance Mixed-Signal (HPMS) chip to a key strategic partner. The rumor mill exploded, and multiple leaks over subsequent months revealed plans for the replacement of the physical volume rocker with solid-state buttons on iPhone 15 Pro models — buttons the HMPS chip would enable.In describing a strategic partner with a “new product” scheduled for the fall, Cirrus is all but naming Apple. It makes further hints when highlighting the “limited visibility into our customer’s future plans for this product,” given Apple’s famous secrecy around the iPhone.The news is likely to polarize iPhone fans. On the one hand, solid-state volume buttons would have likely been more durable and water resistant. There is also the possibility that they could have supported customizable functions in software, including shortcuts and swipe gestures.On the flip side, leaked CADs showed the solid-state buttons to be almost flush with the phone, making them harder to operate through muscle memory, and their need for a dedicated chip to function felt like overengineering to fix a problem no one had.What is likely to remain, however, is the new Action button — a customizable button that will replace the mute switch on iPhone 15 Pro and Pro Max models. The Action button was first introduced on the Apple Watch Ultra and well received.",
    },
    {
      id: 2,
      title: "Microbes discovered that can digest plastics at low temperatures",
      img: "https://i.guim.co.uk/img/media/4d627473cfd1e0b945761054a2200b863b577f18/0_79_2370_1422/master/2370.jpg?width=620&quality=45&dpr=2&s=none",
      desc: "Scientists have found microbes that can do this at 15C, in a potential breakthrough for recycling. Microbes that can digest plastics at low temperatures have been discovered by scientists in the Alps and the Arctic, which could be a valuable tool in recycling.",
      longDesc:"Many microorganisms that can do this have already been found, but they can usually only work at temperatures above 30C (86F). This means that using them in industrial practice is prohibitively expensive because of the heating required. It also means using them is not carbon neutral.Scientists from the Swiss Federal Institute WSL have found microbes that can do this at 15C, which could lead to a breakthrough in microbial recycling. Their findings have been published in the journal Frontiers in Microbiology.Dr Joel Rüthi from WSL and colleagues sampled 19 strains of bacteria and 15 of fungi growing on free-lying or intentionally buried plastic kept in the ground for one year in Greenland, Svalbard and Switzerland. They let the microbes grow as single-strain cultures in the laboratory in darkness at 15C and tested them to see if they could digest different types of plastic.The results showed that the bacterial strains belonged to 13 genera in the phyla actinobacteria and proteobacteria, and the fungi to 10 genera in the phyla ascomycota and mucoromycota. The plastics tested included non-biodegradable polyethylene (PE) and the biodegradable polyester-polyurethane (PUR) as well as two commercially available biodegradable mixtures of polybutylene adipate terephthalate (PBAT) and polylactic acid (PLA)."
    },
    {
      id: 3,
      title: "New Honkai: Star Rail Characters Are Silver Wolf, Luocha, Yukong",
      img: "https://www.siliconera.com/wp-content/uploads/2023/05/yukong-honkai-star-rail-05102023.png?fit=710%2C400",
      desc: "Ahead of official global social media accounts, HoYoVerse revealed on its bilibili channel who the next new characters will be in Honkai Star Rail. Silver Wolf and Luocha will be limited 5-stars and Yukong will be a 4-star, and they’ll likely debut in Honkai Star Rail Version 1.1. Of the three, only Silver Wolf belongs to a faction other than Xianzhou Luofu. [Thanks, Inside Games!]",
      longDesc:"Ahead of official global social media accounts, HoYoVerse revealed on its bilibili channel who the next new characters will be in Honkai Star Rail. Silver Wolf and Luocha will be limited 5-stars and Yukong will be a 4-star, and they’ll likely debut in Honkai Star Rail Version 1.1. Of the three, only Silver Wolf belongs to a faction other than Xianzhou Luofu. [Thanks, Inside Games!].From the tutorial, we know that Silver Wolf is a Quantum/Nihility character in Honkai: Star Rail. She very closely resembles Bronya Zaychik from Honkai Impact 3rd, of which Star Rail is a spin-off of. Silver Wolf has a very hacker-like moveset, in which it looks like she can manipulate the space around her to create constructs from retro video games. Luocha is a traveling merchant who carries around a giant coffin. He is an Imaginary character who is likely of the Abundance Path due to his healing capabilities. Akira Ishida (Athrun from Mobile Suit Gundam SeeD) voices him in the Japanese dub. We already meet him as an NPC in the game as part of the 1.0 Trailblazer Missions.Yukong is Tingyun’s superior, but little else in terms of information is available to us at the moment. As a 4-star, she will likely be available permanently even after the next banners. In Japanese, Yumi Toma (Raine from Tales of Symphonia) is her voice actress.Honkai Star Rail is available on mobile devices and Windows PC. PS4 and PS5 versions will come out in the near future. Silver Wolf, Luocha, and Yukong will all show up soon in future updates of Honkai Star Rail. "
    },


  ];